powerpc/shared: Fix build problem
Since commit 656c21d6af5d ("powerpc/shared: Use static key to detect
shared processor") and 14c73bd344da ("powerpc/vcpu: Assume dedicated
processors as non-preempt"), powerpc test builds may fail with the
following build errors.

./arch/powerpc/include/asm/spinlock.h:39:1: error:
	type defaults to ‘int’ in declaration of ‘DECLARE_STATIC_KEY_FALSE’
./arch/powerpc/include/asm/spinlock.h: In function ‘vcpu_is_preempted’:
./arch/powerpc/include/asm/spinlock.h:44:7: error:
	implicit declaration of function ‘static_branch_unlikely’
./arch/powerpc/include/asm/spinlock.h:44:31: error:
	‘shared_processor’ undeclared

The offending commits use static_branch_unlikely and shared_processor
without adding the include file declaring it.

Cc: Srikar Dronamraju <srikar@linux.vnet.ibm.com>
Cc: Phil Auld <pauld@redhat.com>
Cc: Waiman Long <longman@redhat.com>
Cc: Michael Ellerman <mpe@ellerman.id.au>
Cc: Juri Lelli <juri.lelli@redhat.com>
Fixes: 656c21d6af5d ("powerpc/shared: Use static key to detect shared processor")
Fixes: 14c73bd344da ("powerpc/vcpu: Assume dedicated processors as non-preempt")
Signed-off-by: Guenter Roeck <linux@roeck-us.net>