linux-next: build failure after merge of the powerpc tree
Hi all,

After merging the powerpc tree, today's linux-next build (powerpc
allyesconfig) failed like this:

In file included from <command-line>:32:
./usr/include/asm/vas-api.h:15:2: error: unknown type name '__u32'
   15 |  __u32 version;
      |  ^~~~~
./usr/include/asm/vas-api.h:16:2: error: unknown type name '__s16'
   16 |  __s16 vas_id; /* specific instance of vas or -1 for default */
      |  ^~~~~
./usr/include/asm/vas-api.h:17:2: error: unknown type name '__u16'
   17 |  __u16 reserved1;
      |  ^~~~~
./usr/include/asm/vas-api.h:18:2: error: unknown type name '__u64'
   18 |  __u64 flags; /* Future use */
      |  ^~~~~
./usr/include/asm/vas-api.h:19:2: error: unknown type name '__u64'
   19 |  __u64 reserved2[6];
      |  ^~~~~

Caused by commit

  45f25a79fe50 ("powerpc/vas: Define VAS_TX_WIN_OPEN ioctl API")

uapi headers should be self contained.  I have added the following patch
for today:

From: Stephen Rothwell <sfr@canb.auug.org.au>
Date: Wed, 22 Apr 2020 15:28:26 +1000
Subject: [PATCH] powerpc/vas: uapi headers should be self contained

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>