powerpc/sysdev: Fix compile errors in fsl_85xx_cache_sram.c
Include linux/io.h into fsl_85xx_cache_sram.c to fix
implicit-declaration compile errors:

  arch/powerpc/sysdev/fsl_85xx_cache_sram.c: In function ‘instantiate_cache_sram’:
  arch/powerpc/sysdev/fsl_85xx_cache_sram.c:97:26: error: implicit declaration of function ‘ioremap_coherent’;
    cache_sram->base_virt = ioremap_coherent(cache_sram->base_phys,
                            ^
  arch/powerpc/sysdev/fsl_85xx_cache_sram.c:123:2: error: implicit declaration of function ‘iounmap’;
    iounmap(cache_sram->base_virt);
    ^

Fixes: 6db92cc9d07d ("powerpc/85xx: add cache-sram support")
Signed-off-by: WANG Wenhu <wenhu.wang@vivo.com>
Reviewed-by: Christophe Leroy <christophe.leroy@c-s.fr>
Signed-off-by: Michael Ellerman <mpe@ellerman.id.au>
Link: https://lore.kernel.org/r/20200302053801.26027-1-wenhu.wang@vivo.com