powerpc/shared: include correct header for static key
Recently, the spinlock implementation grew a static key optimization,
but the jump_label.h header include was left out, leading to build
errors:

linux/arch/powerpc/include/asm/spinlock.h:44:7: error: implicit declaration of function ‘static_branch_unlikely’ [-Werror=implicit-function-declaration]
   44 |  if (!static_branch_unlikely(&shared_processor))

This commit adds the missing header.

Fixes: 656c21d6af5d ("powerpc/shared: Use static key to detect shared processor")
Cc: Srikar Dronamraju <srikar@linux.vnet.ibm.com>
Signed-off-by: Jason A. Donenfeld <Jason@zx2c4.com>